-- MySQL Script generated by MySQL Workbench
-- Wed Feb  9 18:37:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward engineering

--SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
--SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
--SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_--ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- DATABASE PrivadasLibertad
-- -----------------------------------------------------
/*
DROP DATABASE IF EXISTS "PrivadasLibertad";

CREATE DATABASE "PrivadasLibertad"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;*/
	
-- -----------------------------------------------------
-- Schema "crowdsourcing"
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS "crowdsourcing";

-- -----------------------------------------------------
-- Table "crowdsourcing"."REGION"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."REGION";
CREATE TABLE IF NOT EXISTS "crowdsourcing"."REGION" (
  "idREGION" INT NOT NULL,
  "nombreRegion" VARCHAR(45) NULL,
  PRIMARY KEY ("idREGION"))
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."COMUNA"
-- -----------------------------------------------------
--DROP TABLE "crowdsourcing"."COMUNA"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."COMUNA" (
  "idCOMUNA" INT NOT NULL,
  "REGION_idREGION" INT NOT NULL,
  "nombreComuna" VARCHAR(45) NULL,
  PRIMARY KEY ("idCOMUNA"),
  --INDEX "fk_COMUNA_REGION_idx" ("REGION_idREGION" ASC) VISIBLE,
  CONSTRAINT "fk_COMUNA_REGION"
    FOREIGN KEY ("REGION_idREGION")
    REFERENCES "crowdsourcing"."REGION" ("idREGION")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."CALLE"
-- -----------------------------------------------------
--DROP TABLE "crowdsourcing"."CALLE"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."CALLE" (
  "idCALLE" INT NOT NULL,
  "REGION_idREGION" INT NOT NULL,
  "COMUNA_idCOMUNA" INT NOT NULL,
  "nombreCalle" VARCHAR(45) NULL,
  PRIMARY KEY ("idCALLE"),
  --INDEX "fk_CALLE_REGION1_idx" ("REGION_idREGION" ASC) VISIBLE,
  --INDEX "fk_CALLE_COMUNA1_idx" ("COMUNA_idCOMUNA" ASC) VISIBLE,
  CONSTRAINT "fk_CALLE_REGION1"
    FOREIGN KEY ("REGION_idREGION")
    REFERENCES "crowdsourcing"."REGION" ("idREGION")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_CALLE_COMUNA1"
    FOREIGN KEY ("COMUNA_idCOMUNA")
    REFERENCES "crowdsourcing"."COMUNA" ("idCOMUNA")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."DIRECCION"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."DIRECCION"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."DIRECCION" (
  "idDIRECCION" INT NOT NULL,
  "CALLE_idCALLE" INT NOT NULL,
  "REGION_idREGION" INT NOT NULL,
  "COMUNA_idCOMUNA" INT NOT NULL,
  "numero" VARCHAR(45) NULL,
  PRIMARY KEY ("idDIRECCION"),
  --INDEX "fk_DIRECCION_CALLE1_idx" ("CALLE_idCALLE" ASC) VISIBLE,
  --INDEX "fk_DIRECCION_REGION1_idx" ("REGION_idREGION" ASC) VISIBLE,
  --INDEX "fk_DIRECCION_COMUNA1_idx" ("COMUNA_idCOMUNA" ASC) VISIBLE,
  CONSTRAINT "fk_DIRECCION_CALLE1"
    FOREIGN KEY ("CALLE_idCALLE")
    REFERENCES "crowdsourcing"."CALLE" ("idCALLE")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_DIRECCION_REGION1"
    FOREIGN KEY ("REGION_idREGION")
    REFERENCES "crowdsourcing"."REGION" ("idREGION")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_DIRECCION_COMUNA1"
    FOREIGN KEY ("COMUNA_idCOMUNA")
    REFERENCES "crowdsourcing"."COMUNA" ("idCOMUNA")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."PERSONA"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."PERSONA"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."PERSONA" (
  "rut" INT NOT NULL,
  "DIRECCION_idDIRECCION" INT NOT NULL,
  "nombrePersona" VARCHAR(45) NULL,
  "apellidoPersona" VARCHAR(45) NULL,
  PRIMARY KEY ("rut"),
  --INDEX "fk_PERSONA_DIRECCION1_idx" ("DIRECCION_idDIRECCION" ASC) VISIBLE,
  CONSTRAINT "fk_PERSONA_DIRECCION1"
    FOREIGN KEY ("DIRECCION_idDIRECCION")
    REFERENCES "crowdsourcing"."DIRECCION" ("idDIRECCION")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."USUARIO"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."USUARIO"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."USUARIO" (
  "PERSONA_rut" INT NOT NULL,
  "contraseña" VARCHAR(45) NOT NULL,
  "fechaRegistro" DATE DEFAULT CURRENT_DATE,
  "ultimoInicio" TIMESTAMP DEFAULT CURRENT_DATE,
  "sesionIniciada" BOOL DEFAULT FALSE,
  "tipoUsuario" VARCHAR(10) NOT NULL,
  "nombreUsuario" VARCHAR(45) UNIQUE NOT NULL,
  "estaEliminado" BOOL  DEFAULT FALSE,
  PRIMARY KEY ("PERSONA_rut"),
  --UNIQUE INDEX "nombreUsuario_UNIQUE" ("nombreUsuario" ASC) VISIBLE,
  CONSTRAINT "fk_USUARIO_PERSONA1"
    FOREIGN KEY ("PERSONA_rut")
    REFERENCES "crowdsourcing"."PERSONA" ("rut")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."ADMIN"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."ADMIN"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."ADMIN" (
  "USUARIO_PERSONA_rut" INT NOT NULL,
  PRIMARY KEY ("USUARIO_PERSONA_rut"),
  CONSTRAINT "fk_ADMIN_USUARIO1"
    FOREIGN KEY ("USUARIO_PERSONA_rut")
    REFERENCES "crowdsourcing"."USUARIO" ("PERSONA_rut")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."INSTITUCION"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."INSTITUCION"
--DROP TABLE "crowdsourcing"."INSTITUCION"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."INSTITUCION" (
  "idINSTITUCION" INT NOT NULL,
  "DIRECCION_idDIRECCION" INT NOT NULL,
  "nombreInstitucion" VARCHAR(45) NULL,
  "tipoInstitucion" VARCHAR(45) NULL,
  PRIMARY KEY ("idINSTITUCION"),
  --INDEX "fk_INSTITUCION_DIRECCION1_idx" ("DIRECCION_idDIRECCION" ASC) VISIBLE,
  CONSTRAINT "fk_INSTITUCION_DIRECCION1"
    FOREIGN KEY ("DIRECCION_idDIRECCION")
    REFERENCES "crowdsourcing"."DIRECCION" ("idDIRECCION")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."VERIFICACION"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."VERIFICACION"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."VERIFICACION" (
  "idVERIFICACION" INT NOT NULL,
  "ADMIN_USUARIO_PERSONA_rut" INT NOT NULL,
  "fechaEmision" DATE DEFAULT CURRENT_DATE,
  "estadoVerificacion" BOOL DEFAULT FALSE,
  PRIMARY KEY ("idVERIFICACION"),
  --INDEX "fk_VERIFICACION_ADMIN1_idx" ("ADMIN_USUARIO_PERSONA_rut" ASC) VISIBLE,
  CONSTRAINT "fk_VERIFICACION_ADMIN1"
    FOREIGN KEY ("ADMIN_USUARIO_PERSONA_rut")
    REFERENCES "crowdsourcing"."ADMIN" ("USUARIO_PERSONA_rut")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."VERIFICADOR"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."VERIFICADOR"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."VERIFICADOR" (
  "USUARIO_PERSONA_rut" INT NOT NULL,
  "INSTITUCION_idINSTITUCION" INT NOT NULL,
  "VERIFICACION_idVERIFICACION" INT NOT NULL,
  PRIMARY KEY ("USUARIO_PERSONA_rut"),
  --INDEX "fk_VERIFICADOR_INSTITUCION1_idx" ("INSTITUCION_idINSTITUCION" ASC) VISIBLE,
  --INDEX "fk_VERIFICADOR_VERIFICACION1_idx" ("VERIFICACION_idVERIFICACION" ASC) VISIBLE,
  CONSTRAINT "fk_VERIFICADOR_USUARIO1"
    FOREIGN KEY ("USUARIO_PERSONA_rut")
    REFERENCES "crowdsourcing"."USUARIO" ("PERSONA_rut")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_VERIFICADOR_INSTITUCION1"
    FOREIGN KEY ("INSTITUCION_idINSTITUCION")
    REFERENCES "crowdsourcing"."INSTITUCION" ("idINSTITUCION")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_VERIFICADOR_VERIFICACION1"
    FOREIGN KEY ("VERIFICACION_idVERIFICACION")
    REFERENCES "crowdsourcing"."VERIFICACION" ("idVERIFICACION")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."INFORMANTE"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."INFORMANTE"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."INFORMANTE" (
  "USUARIO_PERSONA_rut" INT NOT NULL,
  "VERIFICACION_idVERIFICACION" INT NOT NULL,
  "nivelEducacionalInformante" VARCHAR(45) NULL,
  "estadoCivil" VARCHAR(45) NULL,
  "estadoCausa" VARCHAR(45) NULL,
  PRIMARY KEY ("USUARIO_PERSONA_rut"),
  --INDEX "fk_INFORMANTE_VERIFICACION1_idx" ("VERIFICACION_idVERIFICACION" ASC) VISIBLE,
  CONSTRAINT "fk_INFORMANTE_USUARIO1"
    FOREIGN KEY ("USUARIO_PERSONA_rut")
    REFERENCES "crowdsourcing"."USUARIO" ("PERSONA_rut")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_INFORMANTE_VERIFICACION1"
    FOREIGN KEY ("VERIFICACION_idVERIFICACION")
    REFERENCES "crowdsourcing"."VERIFICACION" ("idVERIFICACION")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."CUSTODIA"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."CUSTODIA"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."CUSTODIA" (
  "PERSONA_rut" INT NOT NULL,
  "relacionCarga" VARCHAR(45) NULL,
  "relacionInformante" VARCHAR(45) NULL,
  PRIMARY KEY ("PERSONA_rut"),
  CONSTRAINT "fk_CUSTODIA_PERSONA1"
    FOREIGN KEY ("PERSONA_rut")
    REFERENCES "crowdsourcing"."PERSONA" ("rut")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."CARGA"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."CARGA"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."CARGA" (
  "PERSONA_rut" INT NOT NULL,
  "CUSTODIA_PERSONA_rut" INT NOT NULL,
  "INFORMANTE_USUARIO_PERSONA_rut" INT NOT NULL,
  "relacionInformanteCarga" VARCHAR(45) NULL,
  "edad" INT NULL,
  "nivelEducativo" VARCHAR(45) NULL,
  PRIMARY KEY ("PERSONA_rut"),
  --INDEX "fk_CARGA_CUSTODIA1_idx" ("CUSTODIA_PERSONA_rut" ASC) VISIBLE,
  --INDEX "fk_CARGA_INFORMANTE1_idx" ("INFORMANTE_USUARIO_PERSONA_rut" ASC) VISIBLE,
  CONSTRAINT "fk_CARGA_PERSONA1"
    FOREIGN KEY ("PERSONA_rut")
    REFERENCES "crowdsourcing"."PERSONA" ("rut")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_CARGA_CUSTODIA1"
    FOREIGN KEY ("CUSTODIA_PERSONA_rut")
    REFERENCES "crowdsourcing"."CUSTODIA" ("PERSONA_rut")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_CARGA_INFORMANTE1"
    FOREIGN KEY ("INFORMANTE_USUARIO_PERSONA_rut")
    REFERENCES "crowdsourcing"."INFORMANTE" ("USUARIO_PERSONA_rut")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."CONDENA"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."CONDENA"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."CONDENA" (
  "idCONDENA" INT NOT NULL,
  "INFORMANTE_USUARIO_PERSONA_rut" INT NOT NULL,
  "fechaInicio" DATE NULL,
  "duracion" INT NULL,
  PRIMARY KEY ("idCONDENA"),
  --INDEX "fk_CONDENA_INFORMANTE1_idx" ("INFORMANTE_USUARIO_PERSONA_rut" ASC) VISIBLE,
  CONSTRAINT "fk_CONDENA_INFORMANTE1"
    FOREIGN KEY ("INFORMANTE_USUARIO_PERSONA_rut")
    REFERENCES "crowdsourcing"."INFORMANTE" ("USUARIO_PERSONA_rut")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."MOTIVO"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."MOTIVO"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."MOTIVO" (
  "idMOTIVO" INT NOT NULL,
  "CONDENA_idCONDENA" INT NOT NULL,
  "CONDENA_INFORMANTE_USUARIO_PERSONA_rut" INT NOT NULL,
  "descripcionDelito" VARCHAR(45) NULL,
  PRIMARY KEY ("idMOTIVO"),
  --INDEX "fk_MOTIVO_CONDENA1_idx" ("CONDENA_idCONDENA" ASC, "CONDENA_INFORMANTE_USUARIO_PERSONA_rut" ASC) VISIBLE,
  CONSTRAINT "fk_MOTIVO_CONDENA1"
    FOREIGN KEY ("CONDENA_idCONDENA")
    REFERENCES "crowdsourcing"."CONDENA" ("idCONDENA")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."LOGIN"
-- -----------------------------------------------------
--DROP TABLE IF EXISTS "crowdsourcing"."LOGIN"
CREATE TABLE IF NOT EXISTS "crowdsourcing"."LOGIN" (
  "idLOGIN" INT NOT NULL,
  "USUARIO_PERSONA_rut" INT NOT NULL,
  "nombreUsuarioLogin" VARCHAR(45) NULL,
  "contraseñaLogin" VARCHAR(45) NULL,
  "fechaLogin" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("idLOGIN"),
  --INDEX "fk_LOGIN_USUARIO1_idx" ("USUARIO_PERSONA_rut" ASC) VISIBLE,
  CONSTRAINT "fk_LOGIN_USUARIO1"
    FOREIGN KEY ("USUARIO_PERSONA_rut")
    REFERENCES "crowdsourcing"."USUARIO" ("PERSONA_rut")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;
--------------------------------------------------------
--------------------------------------------------------
-- -----------------------------------------------------
-- SUBSISTEMAS PENITENCIARIOS SOLO MUJERES
-- -----------------------------------------------------
--------------------------------------------------------
-- -----------------------------------------------------
-- Table "crowdsourcing"."cerrado"
-- -----------------------------------------------------
/*REATE TABLE IF NOT EXISTS "crowdsourcing"."cerrado" (
  "cerrado_idcerrado" INT NOT NULL,
  "condenados_24hrs" INT NULL,
  "condenados_falta" INT NULL,
  "condenados_juvenil" INT NULL,
  "imputados" INT NULL,
  "procesados" INT NULL,
  PRIMARY KEY ("cerrado_idcerrado"),
  CONSTRAINT "fk_cerrado_cerrado1"
    FOREIGN KEY ("cerrado_idcerrado")
    REFERENCES "crowdsourcing"."cerrado" ("idcerrado")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."postpenitenciario"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "crowdsourcing"."postpenitenciario" (
  "idpostpenitenciario" INT NOT NULL,
  "control_dl409" VARCHAR(45) NULL,
  "indulto_conmutativo" VARCHAR(45) NULL,
  "oficina_diagnostico_prontuarial" VARCHAR(45) NULL,
  PRIMARY KEY ("idpostpenitenciario"))
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."abierto"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "crowdsourcing"."abierto" (
  "cerrado_idcerrado" INT NOT NULL,
  "condenados_arresto_diurno" INT NULL,
  "condenados_arresto_nocturno" INT NULL,
  "libertad_condicional" INT NULL,
  "SCML" INT NULL,
  "abiertocol" INT NULL,
  PRIMARY KEY ("cerrado_idcerrado"),
  CONSTRAINT "fk_abierto_cerrado1"
    FOREIGN KEY ("cerrado_idcerrado")
    REFERENCES "crowdsourcing"."cerrado" ("idcerrado")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."subsistemas"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "crowdsourcing"."subsistemas" (
  "idsubsistemas" INT NOT NULL,
  "cerrado_idcerrado" INT NOT NULL,
  "postpenitenciario_idpostpenitenciario" INT NOT NULL,
  "abierto_idabierto" INT NOT NULL,
  "fecha_scraping" DATE NULL,
  PRIMARY KEY ("idsubsistemas", "cerrado_idcerrado", "postpenitenciario_idpostpenitenciario", "abierto_idabierto"),
  --INDEX "fk_subsistemas_cerrado1_idx" ("cerrado_idcerrado" ASC) VISIBLE,
  --INDEX "fk_subsistemas_postpenitenciario1_idx" ("postpenitenciario_idpostpenitenciario" ASC) VISIBLE,
  --INDEX "fk_subsistemas_abierto1_idx" ("abierto_idabierto" ASC) VISIBLE,
  CONSTRAINT "fk_subsistemas_cerrado1"
    FOREIGN KEY ("cerrado_idcerrado")
    REFERENCES "crowdsourcing"."cerrado" ("idcerrado")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_subsistemas_postpenitenciario1"
    FOREIGN KEY ("postpenitenciario_idpostpenitenciario")
    REFERENCES "crowdsourcing"."postpenitenciario" ("idpostpenitenciario")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_subsistemas_abierto1"
    FOREIGN KEY ("abierto_idabierto")
    REFERENCES "crowdsourcing"."abierto" ("idabierto")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."metodos_alternativos"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "crowdsourcing"."metodos_alternativos" (
  "abierto_idabierto" INT NOT NULL,
  "remision_condicional_pena" INT NULL,
  "libertad_vigilada_adulto" INT NULL,
  "reclusion_nocturna" INT NULL,
  "remision_condicional" INT NULL,
  "libertad_vigilada" INT NULL,
  "libertad_vigilada_intensiva" INT NULL,
  "reclusion_parcial" INT NULL,
  "psbc" INT NULL,
  "expulsion" INT NULL,
  "reclusion_domiciliaria" INT NULL,
  PRIMARY KEY ("abierto_idabierto"),
  CONSTRAINT "fk_metodos_alternativos_abierto1"
    FOREIGN KEY ("abierto_idabierto")
    REFERENCES "crowdsourcing"."abierto" ("idabierto")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."cerrado"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "crowdsourcing"."cerrado" (
  "cerrado_idcerrado" INT NOT NULL,
  "condenados_24hrs" INT NULL,
  "condenados_falta" INT NULL,
  "condenados_juvenil" INT NULL,
  "imputados" INT NULL,
  "procesados" INT NULL,
  PRIMARY KEY ("cerrado_idcerrado"),
  CONSTRAINT "fk_cerrado_cerrado1"
    FOREIGN KEY ("cerrado_idcerrado")
    REFERENCES "crowdsourcing"."cerrado" ("idcerrado")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."semiabierto"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "crowdsourcing"."semiabierto" (
  "cerrado_idcerrado" INT NOT NULL,
  "condenados_cet_semiabierto" INT NULL,
  PRIMARY KEY ("cerrado_idcerrado"),
  CONSTRAINT "fk_semiabierto_cerrado1"
    FOREIGN KEY ("cerrado_idcerrado")
    REFERENCES "crowdsourcing"."cerrado" ("idcerrado")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."penas_sustitutivas"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "crowdsourcing"."penas_sustitutivas" (
  "abierto_idabierto" INT NOT NULL,
  "domiciliaria_1_2_3_11_primero" INT NULL,
  "domiciliaria_11_segundo" INT NULL,
  "domiciliaria_nocturna_art4" INT NULL,
  "domiciliaria_nocturna_art5" INT NULL,
  PRIMARY KEY ("abierto_idabierto"),
  CONSTRAINT "fk_metodos_alternativos_abierto2"
    FOREIGN KEY ("abierto_idabierto")
    REFERENCES "crowdsourcing"."abierto" ("idabierto")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;


-- -----------------------------------------------------
-- Table "crowdsourcing"."abierto"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "crowdsourcing"."abierto" (
  "cerrado_idcerrado" INT NOT NULL,
  "condenados_arresto_diurno" INT NULL,
  "condenados_arresto_nocturno" INT NULL,
  "libertad_condicional" INT NULL,
  "SCML" INT NULL,
  "abiertocol" INT NULL,
  PRIMARY KEY ("cerrado_idcerrado"),
  CONSTRAINT "fk_abierto_cerrado1"
    FOREIGN KEY ("cerrado_idcerrado")
    REFERENCES "crowdsourcing"."cerrado" ("idcerrado")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
--ENGINE = InnoDB
;
*/

--SET SQL_MODE=@OLD_SQL_MODE;
--SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
--SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
